### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by budziq** [seanmonstar/pretty-env-logger#2]
Hi,

During work on https://github.com/rust-lang-nursery/log/ documentation, we wanted to add link to this crate as one of the most popular implementations. Unfortunately it has no documentation. Currently it does not seam to be intended for 3'rd party adoption. Would you be open to adding few sentences to docs? 

Please refer to: https://github.com/rust-lang-nursery/log/pull/188/commits/dbd3c44bc0b030c3b928635de0e059f55e8ae67b#r119920413

**Comment by seanmonstar** [comment]
Sure! I originally created this crate for myself, and then others said they wished they could use it, so I published it. Haven't thought too much about it since, but I'm sure it could use some touch ups.

**Comment by budziq** [comment]
@seanmonstar could you regenerate the docs? https://docs.rs/pretty_env_logger/*/pretty_env_logger/ still shows the previous version

**Comment by seanmonstar** [comment]
Yep, needed to publish a new version. Done!

**Comment by budziq** [comment]
Thanks! :)
